services:

  app-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  nginx-container:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app-container
